environment:
  matrix:
    - nodejs_version: 'LTS'
    - nodejs_version: 'Current'

install:
  - node --version
  - npm --version
  - ps: Install-Product node $env:nodejs_version
  - set CI=true
  - npm install --global npm@latest
  - set PATH=%APPDATA%\npm;%PATH%
  - npm install -g serverless
  - npm ci
  - node --version
  - npm --version

matrix:
  fast_finish: true

shallow_clone: true

build_script:
  - npm run build

artifacts:
  - path: .serverless
    name: Serverless Package

test: off
