service: rockpaperscissors

provider:
  name: aws
  runtime: nodejs6.10
  stage: demo
  region: eu-central-1
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "apigateway:GET"
      Resource:
        - "arn:aws:apigateway:${self:provider.region}::/restapis*"

plugins:
  - serverless-plugin-typescript
  - serverless-offline
  - serverless-aws-documentation
  - serverless-domain-manager
  - serverless-stack-output

package:
  include:
    src/**/!(*.spec).js
  exclude:
    - node_modules/**/*

functions:
  getSwaggerJson:
    handler: src/swagger/swagger.getSwaggerJson
    description: Returns the Swagger documentation of the API in JSON format.

    environment:
      REGION_NAME: ${self:provider.region}
      REST_API_NAME: ${self:service}
      STAGE_NAME: ${self:provider.stage}
      API_INFO_VERSION: ${file(./swagger/documentation.yml):api.info.version}
      API_INFO_TITLE: ${file(./swagger/documentation.yml):api.info.title}

    events:
      - http:
          path: swagger.json
          method: get
          cors: true

  getHealthCheck:
    handler: src/health/health.getHealthCheck
    description: Returns the result of a quick health check of the API.

    events:
      - http:
          path: health/check
          method: get
          cors: true
          documentation:
            summary: Returns the result of a quick health check of the API.
            tags:
              - Health
            description: Returns the result of a quick health check of the API.
            methodResponses:
              - statusCode: '200'
                description: Returned when the operation is completed successfully.
                responseModels:
                  "application/json": GetHealthCheck
              - ${file(./swagger/error-responses/internal-server-error.yml)}

  getHealthCheckDetailed:
    handler: src/health/health.getHealthCheckDetailed
    description: Returns the result of a detailed health check of the API.

    events:
      - http:
          path: health/detailed
          method: get
          cors: true
          documentation:
            summary: Returns the result of a detailed health check of the API.
            tags:
              - Health
            description: Returns the result of a detailed health check of the API.
            methodResponses:
              - statusCode: '200'
                description: Returned when the operation is completed successfully.
                responseModels:
                  "application/json": GetHealthCheckDetailed
              - ${file(./swagger/error-responses/internal-server-error.yml)}
  getResult:
    handler: src/game/game.getGameResult
    description: Returns a result for a RockPaperScissors two player game.

    environment:
      DEFAULT_MOVE_1: Rock
      DEFAULT_MOVE_2: Paper

    events:
      - http:
          path: game
          method: post
          cors: true
          request:
            schema:
              application/json: ${file(./game/swagger/game_request.json)}
  getCity:
    handler: src/cities/cities.getCity
    description: Returns a single city.

    environment:
      DEFAULT_COUNTRY: Hungary

    events:
      - http:
          path: cities/{id}
          method: get
          cors: true
          request:
            parameters:
              paths:
                id: true
          documentation:
            summary: Get a city.
            tags:
              - City
            description: Returns the specified city.
            pathParams:
              - name: id
                description: The unique identifier of the city to retrieve.
            methodResponses:
              - statusCode: '200'
                description: Returned when the operation is completed successfully.
                responseModels:
                  "application/json": GetCityResponse
              - ${file(./swagger/error-responses/bad-request.yml)}
              - ${file(./swagger/error-responses/forbidden.yml)}
              - ${file(./swagger/error-responses/not-found.yml)}
              - ${file(./swagger/error-responses/internal-server-error.yml)}

custom:
  documentation: ${file(./swagger/documentation.yml)}
  customDomain:
    basePath: "api"
    domainName: rockpaperscissors.ninjabit.com
    certificateName: rockpaperscissors.ninjabit.com
    stage: ${self:provider.stage}
    createRoute53Record: true
  output:
    file: .serverless/output.json
